<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class ArtController extends Controller
{


    public function actionPing()
    {
        return 'Pong';
    }


    public function actionCreatePoster()
    {

        // TODO: check request is coming from logged-in Craft user
        $userAgent = Yii::$app->request->getUserAgent();

        if (!str_starts_with($userAgent, 'Craft') || !str_contains($userAgent, 'Guzzle')) {
            return $this->asJson([
                'success' => false,
                'message' => 'Unauthorized'
            ]);
        }

        // Request params are generated by code, so we can be sure that they are set correctly.
        return $this->asJson(Yii::$app->ffmpeg->createPoster(
            Yii::$app->request->getQueryParam('paths'),
            Yii::$app->request->getQueryParam('seconds'),
            true));
    }

}